package com.example.demo.controller;

import com.example.demo.repository.Timetable;
import com.example.demo.repository.TimetableRepository;
import com.example.demo.repository.User;
import com.example.demo.repository.UserRepository;
import com.example.demo.service.TimetableService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;

//@Controller // This means that this class is a Controller
@RestController // This means that returns a JSON or XML with the users
@RequestMapping(path="/demo", produces="application/json;charset=UTF-8") // This means URL's start with /demo (after Application path)
public class TimetableController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @Autowired
    private TimetableRepository timetableRepository;

    @GetMapping(path="")
    public String test() {
        return "/demo : hello, San";
    }

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @PostMapping(path="/addtime")
    public @ResponseBody String addNewTime (
            @RequestParam String day,
            @RequestParam Integer start,
            @RequestParam Integer end,
            @RequestParam String user) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        TimetableService timetableService = new TimetableService();
        if (!timetableService.validateDay(day) || !timetableService.validateTime(start, end)) {
            Throwable ex = new Throwable();
            throw new ResponseStatusException(
                    HttpStatus.NOT_ACCEPTABLE, "Invalid day, time", ex);
        }
        Timetable n = new Timetable();
        n.setDay(day);
        n.setStart(start);
        n.setEnd(end);
        n.setUser(user);
        timetableRepository.save(n);
        return "Saved";
    }



    @GetMapping(path="/alluser")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/alltime")
    public @ResponseBody Iterable<Timetable> getAllTimeTables() {
        // This returns a JSON or XML with the users
        return timetableRepository.findAll();
    }
}